In [2]:
import pandas as pd 

df = pd.read_csv('D:\\Tuwaiq Academy\\Tuwaiq_Academy_T5_Week_6\\5- Weekly Project\\Datasets\\Traffic Data.csv')
df

traffic_volume    temp  rain_1h  snow_1h  clouds_all weather_main  \
0              1209.0  291.15      0.0      0.0          90         Mist   
1              1248.0  286.01      0.0      0.0           1        Clear   
2              4602.0  293.69      0.0      0.0          75       Clouds   
3              2838.0  262.35      0.0      0.0           1        Clear   
4              5794.0  267.08      0.0      0.0           5        Clear   
...               ...     ...      ...      ...         ...          ...   
19995          2723.0  296.42      0.0      0.0          40       Clouds   
19996          5895.0  285.58      0.0      0.0          40       Clouds   
19997          1132.0  275.30      0.0      0.0           1        Clear   
19998          5525.0  260.94      0.0      0.0          75       Clouds   
19999          5042.0  301.65      0.0      0.0          40       Clouds   

      weather_description            date_time  
0                    mist  2017-08-27 01:00:00  
1            sky is clear  2018-09-06 23:00:00  
2           broken clouds  2017-08-25 18:00:00  
3            sky is clear  2017-11-09 22:00:00  
4            sky is clear  2017-11-09 15:00:00  
...                   ...                  ...  
19995    scattered clouds  2018-06-06 21:00:00  
19996    scattered clouds  2017-10-25 15:00:00  
19997        sky is clear  2018-03-28 23:00:00  
19998       broken clouds  2018-02-12 15:00:00  
19999    scattered clouds  2018-05-31 18:00:00  

[20000 rows x 8 columns]

In [3]:
df.set_index('date_time', inplace=True)
df.sort_index()
df

traffic_volume    temp  rain_1h  snow_1h  clouds_all  \
date_time                                                                   
2017-08-27 01:00:00          1209.0  291.15      0.0      0.0          90   
2018-09-06 23:00:00          1248.0  286.01      0.0      0.0           1   
2017-08-25 18:00:00          4602.0  293.69      0.0      0.0          75   
2017-11-09 22:00:00          2838.0  262.35      0.0      0.0           1   
2017-11-09 15:00:00          5794.0  267.08      0.0      0.0           5   
...                             ...     ...      ...      ...         ...   
2018-06-06 21:00:00          2723.0  296.42      0.0      0.0          40   
2017-10-25 15:00:00          5895.0  285.58      0.0      0.0          40   
2018-03-28 23:00:00          1132.0  275.30      0.0      0.0           1   
2018-02-12 15:00:00          5525.0  260.94      0.0      0.0          75   
2018-05-31 18:00:00          5042.0  301.65      0.0      0.0          40   

                    weather_main weather_description  
date_time                                             
2017-08-27 01:00:00         Mist                mist  
2018-09-06 23:00:00        Clear        sky is clear  
2017-08-25 18:00:00       Clouds       broken clouds  
2017-11-09 22:00:00        Clear        sky is clear  
2017-11-09 15:00:00        Clear        sky is clear  
...                          ...                 ...  
2018-06-06 21:00:00       Clouds    scattered clouds  
2017-10-25 15:00:00       Clouds    scattered clouds  
2018-03-28 23:00:00        Clear        sky is clear  
2018-02-12 15:00:00       Clouds       broken clouds  
2018-05-31 18:00:00       Clouds    scattered clouds  

[20000 rows x 7 columns]

In [4]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()

df[['weather_description', 'weather_main']] = oe.fit_transform(df[['weather_description', 'weather_main']])
df

traffic_volume    temp  rain_1h  snow_1h  clouds_all  \
date_time                                                                   
2017-08-27 01:00:00          1209.0  291.15      0.0      0.0          90   
2018-09-06 23:00:00          1248.0  286.01      0.0      0.0           1   
2017-08-25 18:00:00          4602.0  293.69      0.0      0.0          75   
2017-11-09 22:00:00          2838.0  262.35      0.0      0.0           1   
2017-11-09 15:00:00          5794.0  267.08      0.0      0.0           5   
...                             ...     ...      ...      ...         ...   
2018-06-06 21:00:00          2723.0  296.42      0.0      0.0          40   
2017-10-25 15:00:00          5895.0  285.58      0.0      0.0          40   
2018-03-28 23:00:00          1132.0  275.30      0.0      0.0           1   
2018-02-12 15:00:00          5525.0  260.94      0.0      0.0          75   
2018-05-31 18:00:00          5042.0  301.65      0.0      0.0          40   

                     weather_main  weather_description  
date_time                                               
2017-08-27 01:00:00           5.0                 16.0  
2018-09-06 23:00:00           0.0                 25.0  
2017-08-25 18:00:00           1.0                  1.0  
2017-11-09 22:00:00           0.0                 25.0  
2017-11-09 15:00:00           0.0                 25.0  
...                           ...                  ...  
2018-06-06 21:00:00           1.0                 23.0  
2017-10-25 15:00:00           1.0                 23.0  
2018-03-28 23:00:00           0.0                 25.0  
2018-02-12 15:00:00           1.0                  1.0  
2018-05-31 18:00:00           1.0                 23.0  

[20000 rows x 7 columns]

In [5]:
len(df)

20000

In [6]:
from sklearn.model_selection import train_test_split
train_val , test = train_test_split(df, shuffle=False, test_size=0.2)
train , val = train_test_split(df, shuffle=False, test_size=0.2)
train.shape, test.shape, val.shape

((16000, 7), (4000, 7), (4000, 7))

In [7]:
train_traget = train[['traffic_volume', 'temp']].iloc[6:]
test_traget = test[['traffic_volume', 'temp']].iloc[6:]
val_traget = val[['traffic_volume', 'temp']].iloc[6:]

In [8]:
from keras.utils import timeseries_dataset_from_array

# timeseries_dataset_from_array?
Xy_train = timeseries_dataset_from_array(train, targets=train_traget, sequence_length=6, shuffle=False)
Xy_test = timeseries_dataset_from_array(test, targets=test_traget, sequence_length=6, shuffle=False)
Xy_val = timeseries_dataset_from_array(val, targets=val_traget, sequence_length=6, shuffle=False)

In [9]:
for x, y in Xy_train:
    print(x, y)

tf.Tensor(
[[[1.2090e+03 2.9115e+02 0.0000e+00 ... 9.0000e+01 5.0000e+00 1.6000e+01]
  [1.2480e+03 2.8601e+02 0.0000e+00 ... 1.0000e+00 0.0000e+00 2.5000e+01]
  [4.6020e+03 2.9369e+02 0.0000e+00 ... 7.5000e+01 1.0000e+00 1.0000e+00]
  [2.8380e+03 2.6235e+02 0.0000e+00 ... 1.0000e+00 0.0000e+00 2.5000e+01]
  [5.7940e+03 2.6708e+02 0.0000e+00 ... 5.0000e+00 0.0000e+00 2.5000e+01]
  [4.2570e+03 2.9366e+02 0.0000e+00 ... 7.5000e+01 6.0000e+00 1.7000e+01]]

 [[1.2480e+03 2.8601e+02 0.0000e+00 ... 1.0000e+00 0.0000e+00 2.5000e+01]
  [4.6020e+03 2.9369e+02 0.0000e+00 ... 7.5000e+01 1.0000e+00 1.0000e+00]
  [2.8380e+03 2.6235e+02 0.0000e+00 ... 1.0000e+00 0.0000e+00 2.5000e+01]
  [5.7940e+03 2.6708e+02 0.0000e+00 ... 5.0000e+00 0.0000e+00 2.5000e+01]
  [4.2570e+03 2.9366e+02 0.0000e+00 ... 7.5000e+01 6.0000e+00 1.7000e+01]
  [3.7070e+03 2.9275e+02 0.0000e+00 ... 4.0000e+01 6.0000e+00 1.9000e+01]]

 [[4.6020e+03 2.9369e+02 0.0000e+00 ... 7.5000e+01 1.0000e+00 1.0000e+00]
  [2.8380e+03 2.6235e+0

In [12]:
X_train, y_train = next(iter(Xy_train))
X_test, y_test = next(iter(Xy_test))
X_val, y_val = next(iter(Xy_val))

In [18]:
X_train.shape

TensorShape([128, 6, 7])

In [22]:
Xy_train

<_BatchDataset element_spec=(TensorSpec(shape=(None, None, 7), dtype=tf.float64, name=None), TensorSpec(shape=(None, 2), dtype=tf.float64, name=None))>

In [27]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Dropout
window_len = 6

model = Sequential([
    SimpleRNN(50, return_sequences=True, input_shape=(window_len, 7), activation='tanh'),
    Dropout(0.5),
    SimpleRNN(50),
    Dropout(0.5),
    Dense(2, activation='relu')
])

model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mae'])

model.summary()


C:\Users\abo_O\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_8 (SimpleRNN)        │ (None, 6, 50)          │         2,900 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 6, 50)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_9 (SimpleRNN)        │ (None, 50)             │         5,050 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 50)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 2)              │           102 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,052 (31.45 KB)

 Trainable params: 8,052 (31.45 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
from keras.callbacks import ModelCheckpoint, EarlyStopping
checkpoints = ModelCheckpoint(filepath = 'my_weights.keras', save_best_only = True)

early_stopping = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)

model.fit(X_train, y_train,
          validation_data=(X_val, y_val),
          epochs=100,
          batch_size=32,
          verbose=1,
          callbacks= [checkpoints, early_stopping])

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 4s 175ms/step - loss: 8223887.0000 - mae: 1897.7384 - val_loss: 7002833.0000 - val_mae: 1708.4307
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 7866443.5000 - mae: 1832.9769 - val_loss: 7001912.0000 - val_mae: 1708.1520
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 8497414.0000 - mae: 1948.1456 - val_loss: 6999087.5000 - val_mae: 1707.5129
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 7835456.0000 - mae: 1831.1332 - val_loss: 6996016.0000 - val_mae: 1706.8271
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 7593342.5000 - mae: 1793.9241 - val_loss: 6993070.5000 - val_mae: 1706.1616
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 7272474.0000 - mae: 1755.8800 - val_loss: 6990324.0000 - val_mae: 1705.5459
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 8016049.0000 - mae: 1846.1252 - val_loss: 6987784.0000 - val_mae: 1704.9879
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 748

In [25]:
# Let's do the prediction and check performance metrics
train_predict=model.predict(X_val)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step  


In [26]:
from sklearn.metrics import mean_squared_error
import math
print(math.sqrt(mean_squared_error(y_val, train_predict)))

2627.9185793398515
